version: "3.2"

services: 
  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - "grafana_vol:/var/lib/grafana"
    ports:
      - "8090:3000"
    networks:
      - net-monitoring

  influxdb:
    container_name: influxdb
    image: "influxdb"
    volumes:
      - "influxdb_vol:/var/lib/influxdb"
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_USER=admin  
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=telegraf
    ports:
      - "8086:8086"
    networks:
      - net-monitoring
volumes:
  grafana_vol:
  influxdb_vol:

networks:
  net-monitoring:
    driver: bridge
